AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/Documentation:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: true