AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'

plugins:
  - rubocop-minitest
  - rubocop-rake

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

Layout/ExtraSpacing:
  AllowForAlignment: true

Metrics/MethodLength:
  Exclude:
    - "test/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "test/**/*"